### ISSUE TITLE
Does not compile with current LLVM

### ISSUE THREAD

**Issue by yig** [simit-lang/simit#9] opened 2016-08-04 18:15 UTC
I installed the current LLVM (`brew install llvm`), which is version 3.8.1. Compiling gives me the following errors.

```
[ 35%] Building CXX object src/CMakeFiles/simit.dir/backend/llvm/llvm_backend.cpp.o
/Users/yotam/Work/ext/simit/src/backend/llvm/llvm_backend.cpp:1589:14: error: no matching member function for call to 'insert'
    symtable.insert(*simitArgIt, llvmArgIt);
    ~~~~~~~~~^~~~~~
/Users/yotam/Work/ext/simit/src/util/scopedmap.h:41:8: note: candidate function not viable: no known conversion from
      'llvm::ilist_iterator<llvm::Argument>' to 'llvm::Value *const' for 2nd argument
  void insert(const Key &symbol, const Value &value) {
       ^
/Users/yotam/Work/ext/simit/src/util/scopedmap.h:46:8: note: candidate function not viable: requires single argument 'symVal', but 2
      arguments were provided
  void insert(const std::pair<Key, Value> &symVal) {
       ^
/Users/yotam/Work/ext/simit/src/backend/llvm/llvm_backend.cpp:1594:14: error: no matching member function for call to 'insert'
    symtable.insert(*simitResIt, llvmArgIt);
    ~~~~~~~~~^~~~~~
/Users/yotam/Work/ext/simit/src/util/scopedmap.h:41:8: note: candidate function not viable: no known conversion from
      'llvm::ilist_iterator<llvm::Argument>' to 'llvm::Value *const' for 2nd argument
  void insert(const Key &symbol, const Value &value) {
       ^
/Users/yotam/Work/ext/simit/src/util/scopedmap.h:46:8: note: candidate function not viable: requires single argument 'symVal', but 2
      arguments were provided
  void insert(const std::pair<Key, Value> &symVal) {
       ^
2 errors generated.
```

**Comment by fredrikbk** [comment] 2016-08-04 21:40
I assume you are linking Simit to llvm 3.8.1, as opposed to using clang+llvm 3.8.1 to compile Simit? We currently only support linking to llvm 3.4.2 for GPU-specific reasons, but we're planning to support linking to the new version of llvm in the near future. See the README for more details.

**Comment by fredrikbk** [comment] 2016-08-12 14:57
Duplicate of #21

**Closed by fredrikbk** 2016-08-12 14:57 UTC
Labels: duplicate
