### ISSUE TITLE
It is not compiled on VirtualBox with LinuxMint 18

### ISSUE THREAD

**Issue by qwertyuiop7370** [simit-lang/simit#20] opened 2016-08-12 12:10 UTC
— Debug Build
— Found Eigen
— Shared library
— Building without gpu-backend
— Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR) 
— Could NOT find GLUT (missing:  GLUT_glut_LIBRARY GLUT_INCLUDE_DIR) 
Could not find OpenGL or GLUT so simviz will not be built
— Found LLVM: llvm-config (version "3.8.0")
— Configuring done
— Generating done
...
simit/src/runtime.cpp:327:64:   required from here
/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:32:40: error: static assertion failed: THIS_METHOD_IS_ONLY_FOR_COLUMN_MAJOR_MATRICES
     #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);
e.t.c.

**Comment by fredrikbk** [comment] 2016-08-12 14:58
We currently only officially support linking to llvm 3.4.2. We do not officially support linking to llvm 3.8.0 yet. See #21 for more information.

Closing as duplicate.

**Comment by fredrikbk** [comment] 2016-08-12 15:00
Reopening because the error seems to be with our use of LLVM

**Comment by stephenchouca** [comment] 2016-09-09 17:41
Duplicate of #62

**Closed by stephenchouca** 2016-09-09 17:41 UTC
Labels: duplicate
